---

- name: Get Facts with NAPALM
  hosts: all

  tasks:
  - name: get facts from device
    napalm_get_facts:
      hostname={{ inventory_hostname }}
      username={{ username }}
      password={{ password }}
      dev_os={{ dev_os }}
      filter='facts'
      #filter='facts,interfaces,bgp_neighbors'
    register: result

  - name: print data
    debug: var=result
